EBWiki/EBWiki

app/views/layouts/application.html.erb

Previously popover and tooltip failed because they would not run on pageload when returning to the homepage from a secondary page. Now the javascript runs both on document ready and pageload.

Fix popover and tooltip javscript to work when returning to homepage.

---

config/initializers/split.rb

Basic authentication prevents unauthorized users from accessing our A/B
tests and potentially altering the tests or results.
However, ultimately we should be looking for a better solution --
either by creating a subroute within the rails_admin panel or using
Pundit or CanCanCan for more robust authorizations

Adding basic authenticaion for Issue #183

---

config/initializers/split.rb
config/routes.rb
spec/features/admin_spec.rb

also added to existing admin specs to confirm that the correct pages are
shown when the user is not logged in or is logged in as an admin user.
ultimately, we need to more gracefully handle non-admin users in this
case, but i don't think that should hold us up from pushing to
production.

Re-branched from master to add authentication for #183

---

app/views/analytics/index.html.erb

temporarily commented out comments (ironically).  Also, this views count
is on the entire Visit model. It would be better to count only the views
in the last 30 days but for some reason counting on @visits returns nil
despite working correctly on the Visit model as a whole.

for #145 adding views count

---

config/sitemap.rb

I just rebased this branch.  We now have several hundred agency pages that we could get indexed for search. I think this makes sense to do. I believe I have done this correctly to create a separate sitemap for agencies, but want code review before merging. Previous commit message below:
I didn't want to push this without checking in with @trystant first.
This branch contains the following changes to the sitemap config:
1. Added a line to create_index within the sitemap which causes an index
file to be created to reference multiple sitemaps
2. Added back the conditional to store sitemaps only if env==production.
Not sure why we had commented that out.
3. Added a second generator to create another sitemap with the filename
'agencies' to house urls for the agency show pages. I added the …

for #674 fixes and additions to sitemap config file

---

Gemfile
Gemfile.lock
config/schedule.rb
db/seeds.rb
lib/tasks/autobus_cleanup.rake

This task basically takes our current Autobus storage limit of 10gb and
compares that to the total size of all of our backup snapshots. If we
are over the limit, the task will delete the oldest snapshot until we
are back under the limit.
This will likely not be an issue for several months, but we are being
proactive.

Adding scheduled task to clean backups

---

app/models/agency.rb
app/models/article.rb
db/migrate/20170519002221_add_lat_lng_to_agencies.rb
db/schema.rb
lib/tasks/geocode_data.rake
spec/controllers/articles_controller_spec.rb
spec/controllers/maps_controller_spec.rb
spec/factories/agencies.rb
spec/factories/state.rb
spec/models/agency_spec.rb
spec/models/article_spec.rb
spec/support/geocoder.rb

This was written to resolve issue #881 and #834 .
Adds a slight modification of the rake task from the geocoder docs for the back-generation of article coordinates. The command is to run that is:
`rake geocode_data:all CLASS=Model SLEEP=0.25 BATCH=100`

Geocoding Improvements

---

app/models/user.rb

This commit updates the process for creating a user by scheduling the `add_to_mailchimp` method to execute after the user account is created.  This change will allow users to be created both via Devise as well as `User.create`.
This commit unblocks progress on issue #1003.

Updates user creation process

---

app/models/user.rb
app/models/user_observer.rb
app/services/add_user_to_mailchimp.rb
app/services/service.rb
app/views/user_notifier/welcome_email.html.erb
db/seeds.rb

Refactors functionality for adding users to mailchimp as a service object.  By doing so, this should resolve the issues of accessing the subscribed value for a user in multiple places.
This code will unblock work for Issue #1003.

Refactors functionality for adding users to mailchimp

---

spec/factories/agencies.rb
spec/helpers/agencies_helper_spec.rb
spec/models/agency_spec.rb
spec/support/geocoder.rb

Refactors the agency factory to use the least amount of data possible for creation.  This should speed up tests over time, especially once the state factory becomes a fixture file.  Also replaces usage of the agency factory with `Agency.new` where possible, again speeding up tests.

Refactors agency factory.

---

app/models/article.rb
spec/models/article_spec.rb

This PR adds specs for 2 out of 3 of the current scopes for the `Article` model (the remaining scope will be redone as multiple scopes).  The PR also alters `article_spec` to follow the style of `agency_spec`.

Adds specs for article scopes

---

app/controllers/analytics_controller.rb
app/models/article.rb
spec/models/article_spec.rb

Previously, the `article` model had a scope for `property_count_over_time`, where you could specify the property (e.g., `date`, `created_at`, etc) and the time period and it would return the number of applicable articles.  Since we only called this for a couple of properties and durations, this PR refactors that scope by replacing it with multiple scopes for each property that take a duration as a parameter.  The new scopes return the Activerecord relation, and when the scope is called the calling function is responsible for using method chaining to obtain the count.  This also opens the interface and makes it easier to reuse the scope as needed.

Refactors article scope for count over time for clarity.

---

app/controllers/agencies_controller.rb
app/models/agency.rb
app/models/state.rb
app/views/agencies/show.html.erb
spec/models/agency_spec.rb

The branch name here is a bit of a misnomer, because in the process of adding this spec I realized that this particular scope shouldn't exist.  The scope was being used to determine the name of the state of an agency within the `agency#show` view.  Instead, this PR uses a class method on the `Agency` model to retrieve the corresponding state name, and passes that value as an instance variable from the controller to the view template.

Refactors state from agency scope

---

app/models/article.rb
app/models/follow.rb
app/models/visit.rb
app/views/analytics/_top_metrics.html.erb
spec/factories/visit.rb
spec/models/article_spec.rb
spec/models/follow_spec.rb
spec/models/visit_spec.rb

This branch originally started with a hotfix for the `Article.created_this_month` scope.  However, this PR also includes additional specs and refactoring related to calculating statistics for various models.  This PR also contains specs and refactoring related to scopes for the `Visit` model.  Finally, this PR changes the method `mom_uniq_follows_growth` to `mom_unique_follows_growth` - not really a reason to shorten the word "unique".

Adds specs for statistics methods and refactoring for related models

---

app/controllers/analytics_controller.rb
app/models/article.rb
app/models/follow.rb
app/models/visit.rb
app/views/analytics/index.html.erb
spec/factories/article.rb
spec/factories/visit.rb
spec/models/article_spec.rb

This PR changes all instances of `Date.today` and `Time.now` to `Time.current` to account for time zones.

Hotfix to account for timezones

---

app/controllers/analytics_controller.rb

This PR corrects the query used to generate the statistics for cases occurring within the past 30 days.

Corrects stat for newest cases based on incident date on analytics page.

---

app/controllers/articles_controller.rb
app/helpers/articles_helper.rb
app/views/articles/index.html.erb
spec/views/articles/index.html.erb_spec.rb

This PR refactors the recently updated cases section in `app/views/articles/index.html.erb`.  Specifically, the database query is performed in the corresponding controller action, and the number column is removed.
This PR addresses Issue #922.

Refactors recently updated cases section in cases view.

---

app/controllers/application_controller.rb
app/controllers/conversations_controller.rb
app/helpers/application_helper.rb
app/views/conversations/_form.html.erb
app/views/kaminari/_page.html.erb
app/views/layouts/_header.html.erb
spec/views/articles/index.html.erb_spec.rb
spec/views/articles/show.html.erb_spec.rb

This PR refactors various partials by removing logic and performing queries and Ruby methods in the corresponding controllers and helpers.
There is one gripe I have about this - I updated the header partial to use an instance variable for a list of states, rather than performing the query in the partial.  However, all I could do was set the instance variable via a `before_action` callback in the controller and just call it in the partial.  For some reason, I can't pass the values along in the partial as a local variable - it complains about an undefined local method or variable.  However, since we will be moving towards defining the states in a YAML file rather than doing a database query each time, this is a good compromise in the meantime.
This PR addresses issues #923, #924, and #925.

Removes logic from partials.

---

config/sitemap.rb

- config/sitemap.rb - Changes case_folowers_path to
cases_followers_path to fix error reported in sitemap.
Updates #1411
- [ X ] Include a description of the changes?
- [ X ] Mention the issue the PR addresses?
- [ N/A ] Include screenshots of any changes to the UI?
- [ X ] Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?
There isn't a spec for this because `config/sitemap.rb` is a generated file that has been modified.  The fix for this is one character.

Fixed cases_followers_path reference to fix #1411

---

app/views/mailboxer/message_mailer/new_message_email.text.erb
app/views/mailboxer/message_mailer/reply_message_email.text.erb
app/views/mailboxer/notification_mailer/new_notification_email.html.erb
app/views/mailboxer/notification_mailer/new_notification_email.text.erb

This PR uses the `sanitize` helper to remove logic in email templates that removed any suspicious tags and formatting.  This PR addresses issues #926 and #1280.  No new specs are necessary at this time.

Uses sanitize helper to clean up logic in email templates.

---

docs/DEVELOPMENT.md

Within DEVELOPMENT.md, this PR:
* Adds links to local dev environment set up guides  
* Changes section on finishing a ticket to a general timeline of working on an issue
* Adds table of contents

[ci_skip] Makes changes to DEVELOPMENT.md

---

app/views/cases/index.html.erb

This removes the `ab_test` partial from the cases index view.

Removes ab_test layout from cases index view.

---

docs/DEVELOPMENT.md

Makes section on general timeline more clear about what contributor does and what maintainer does.  Adds section on how to restore a backup dump to local database.

Updates docs/DEVELOPMENT.md

---

app/controllers/cases_controller.rb
spec/controllers/cases_controller_spec.rb

Overall, there was an error occurring rendering the 'edit' template after a failed update. These changes were placed to stop that error from occurring.
- app/controllers/cases_controller.rb - Added Category.all & State.all
to the edit form so that the page renders successfully
- spec/controllers/cases_controller_spec.rb - Added specs to confirm that
those required values are in the rendered template
Updates #1556, #1557

Put in fix for case editing issue

---

spec/controllers/analytics_controller_spec.rb
spec/controllers/comments_controller_spec.rb
spec/controllers/conversations_controller_spec.rb

Fixes the deprecation warning raised by rspec because of using `should` syntax. The issue is referenced [here](https://github.com/EBWiki/EBWiki/issues/1494).
While addressing this issue, I refactored `comments_controller_spec` to  DRY it up. Also, looking at the specs in the `Case Comments` block, it's my opinion that they are more model related than controller related. Are they be better suited for the model spec, i.e `comments_spec.rb`? If so, we can move them.

Resolve deprecation warning

---

app/models/case.rb
spec/models/case_spec.rb

Addresses issue [1576](https://github.com/EBWiki/EBWiki/issues/1576)
- A spec already exists to verify that a case cannot be created without a date. So I added one to verify that a case cannot be created with a date in the future
- I found it necessary to keep the logic that checks if date is present in `case_date_cannot_be_in_the_future`. The reason is that since we are checking that `date > Date.current`, then we should verify that date is not nil. I'm happy to hear other approaches/suggestions  on this though

Add spec to test validate future dates

---

Gemfile
Gemfile.lock
config/initializers/devise.rb

Update gem devise to 4.0.3
- Solves #1730

Update gem devise and remove deprecation warning #1730

---

app/views/static/guidelines.html.erb

(New issue, quick fix) Corrected a typo on the guidelines page - 'links' was written as 'inks' under "How to Edit Existing Cases", the last line.

corrected a typo on the guidelines page - 'links' was written as 'inks'

---

Gemfile
Gemfile.lock

Remove rails-observer gem 
Solves #1702

Remove rails-observer gem  #1702

---

app/controllers/organizations_controller.rb

In the organizations controller, I removed the ```respond_to blocks```  and just rendered/redirected the corresponding pages directly.

for #2098 Removed respond_to blocks in the organizations controller

---

app/services/determine_visits_to_cases.rb

Removed unnecessary begin..rescue..end block in ```app/services/determine_visits_to_cases.rb```

for #2109 Removed unnecessary begin..rescue..end block

---

app/views/user_notifier/send_followers_email.html.erb
spec/mailers/user_notifier_spec.rb

closes #2093
In the user notifier spec, remove the before block in the send_follower_email spec.

[2093] Remove before test block in mailer spec

---

app/views/agencies/edit.html.erb

closes #2295
Display Agency name on edit agency page

[#2295]Display Agency name on edit agency page

---

app/controllers/agencies_controller.rb

This pr define @agency variable directly in each actions rather than having before_action
Fixes #2158

Set instance variable in agency controller actions

---

app/controllers/cases_controller.rb

Replace instances of make_undo_link comments with a flash message 
- Solves #1894

Replace instances of make_undo_link comments with a flash message #1894

---

db/migrate/20180911071251_edit_comment_to_versions.rb
db/structure.sql

Add an empty string as the default for comments in versions
- Solves  #2405

Add an empty string as the default for comments in versions #2405

---

db/migrate/20180926083147_validate_name_presence_on_subjects.rb
db/structure.sql

Add a database constraint that requires the name column for subjects to not be nil.
Solves #2451

Add db validation presence validation on subjects' name #2451

---

db/migrate/20180926085044_validate_name_presence_on_agencies.rb
db/structure.sql

Add a database constraint that requires the name column for agencies to not be nil.
Solves #2450

Db validation for agency name presence #2450

---

app/models/case.rb
db/migrate/20181003130555_add_fk_subjects_cases_cascade.rb
db/structure.sql

Add database constraint between cases and subjects with the option on_delete: :cascade
Issue: https://github.com/EBWiki/EBWiki/issues/2454

Add database constraint between cases and subjects with the option on_delete: :cascade

---

config/routes.rb
spec/features/admin_visits_analytics_page_spec.rb

Update the analytics route to be the following:
```ruby
get '/analytics', to: 'analytics#index'
```
Also update corresponding spec.
Issue: #2492

#2492 update analytics route

---

app/views/cases/_form.html.erb

This commit changes how the error message is displayed when viewing
cases.
See #2549

Refactor error message display for cases

---

db/migrate/20181003112438_add_not_nil_constraint_to_cases.rb
db/structure.sql

Issue: https://github.com/EBWiki/EBWiki/issues/2446
Added migration with not null constraint on table cases on column city

Add database constraint for table cases on column city

---

db/migrate/20181025220728_add_slugs_to_ethnicities.rb
db/structure.sql

The database looks like it was requiring slugs for ethnicities when seeding the database, this pull request includes a migration that adds the slug column to the ethnicities database
Issue: https://github.com/EBWiki/EBWiki/issues/2626
- [√] Include a description of the changes?
- [√] Mention the issue the PR addresses?

add slugs column to ethnicities table

---

app/controllers/cases_controller.rb
spec/controllers/cases_controller_spec.rb
spec/features/editor_saves_case_spec.rb

- app/controllers/cases_controller.rb - Added the @genders variable
to the failure save on the create method
- spec/controllers/cases_controller_spec.rb - Spec that confirms that
the genders variable has been assigned
- spec/features/editor_saves_case_spec.rb - Feature spec to show that
the new case page will display properrly if a user tries to save
and fails
Updates #2610

Fixing new case not re-rendering upon failure

---

app/views/cases/_form.html.erb

Changed one line in the form to clear the summary field in the edit form.

for #2490 fixing summary field to be clear when user edits case

---

lib/tasks/versions.rake
spec/lib/tasks/versions_spec.rb

Issue: https://github.com/EBWiki/EBWiki/issues/2406
Create a rake task to set the values of comments in versions table.
The task can be run using: `rake versions:set_nil_comment`

Create a rake task to set the values of comments in versions table

---

app/views/cases/_thumbnail.html.erb
app/views/cases/index.html.erb

This PR moves the code for the case thumbnails in `cases#index` to a separate partial.  It also does some minor cleanup/refactoring of classes and indentation.  Finally, it removes the blurb from the mask on the thumbnail.

Moves code for case thumbnail in index to separate partial.

---

app/assets/stylesheets/cases.scss

The more hotfixes, the merrier apparently.  But this will remove the scroll bar from the front page gallery.
Will merge immediately after tests pass.

Removes CSS rule that produces scroll bar

---

app/controllers/users_controller.rb
app/views/agencies/show.html.erb
app/views/cases/_index_thumbnail.html.erb
app/views/cases/_show_thumbnail.html.erb
app/views/cases/_thumbnail.html.erb
app/views/cases/index.html.erb
app/views/users/show.html.erb

Adds partials to render case thumbnails on agency and user show views and does minor refactoring. 
This also includes code to skip using Bullet for `users#show`.  If Bullet is enabled, then it will complain that we should use eager loading to retrieve the state for each case.  However, doing so is not currently possible given the configuration of users, cases, and states - we'd need to change that in a sense, and that's not the point of this PR.  Hence, a filter applied to only that controller.

Adds partials for case thumbnails

---

Gemfile
Gemfile.lock
app/controllers/agencies_controller.rb
app/models/agency.rb
app/views/agencies/_form.html.erb
app/views/agencies/show.html.erb
config/locales/en.yml
config/locales/simple_form.en.yml
db/migrate/20190420191754_remove_jurisdiction_type_from_agencies.rb
db/structure.sql
spec/models/agency_spec.rb

-------------------------------------------------------------------------------------------------
As noted in Slack, this PR ended up being a lot bigger than expected due to some accidental data erasure.  What this PR ultimately does is complete adding jurisdiction via PostGres and ActiveRecord enum functionality and removes the old jurisdiction enum created using EnumeratedType.  It also includes some refactoring for the form for agencies and removing unused code elsewhere.

Add jurisdiction enum

---

Gemfile
Gemfile.lock
config/environments/production.rb

Adds lograge gem and updates production config file to use lograge instead of default logger.  Note that lograge is configured to include a timestamp, the host, and a user_id (if applicable) for each request.  If desired, lograge can be configured to save the output of the default Rails logger in a separate log file.
Overall, I believe that using lograge will simplify debugging in the log run.  lograge replaces the standard Rails default logging output, which is usually several lines, with a single line output.  It doesn't do this for exceptions, which will make it easier to note those as well in production logs.

Adds lograge gem

---

Gemfile
Gemfile.lock
config/environments/staging.rb

Removes heroku deflate gem - no longer necessary when using updated stack in Heroku.  Changes deprecated configuration for static files in staging.

Removes heroku deflate gem

---

Gemfile
Gemfile.lock

This change will replace the `sass-rails` gem with the `sassc-rails` gem.  As noted [here](https://github.com/sass/ruby-sass), the original Ruby implementation of Sass has been deprecated and EOL was in March.  The `sass-rails` gem is supposed to get an upgrade to `sassc`, but it's unclear when that will happen, so the change to the gem was made.  The only other gem we have that depends on `sass-rails` is `rails_admin`, but based on [this](https://github.com/sferik/rails_admin/pull/3072) it's unclear when or if that change will occur.
Edit: Actually, it should be noted that `rails_admin` has been updated to use `sassc-rails` as part of 2.0.0.rc - as such, we will wait for the official release of version 2 before upgrading that gem.

Replaces sass-rails with sassc-rails due to gem deprecation.

---

config/initializers/session_store.rb

Looks like the Rails upgrade overwrote the initializer to use the cookie store as default.  This restores that setting back to using the `activerecord_session_store` gem.

Changes the session store to the active record session store gem.

---

app/inputs/date_picker_input.rb
app/inputs/datetime_picker_input.rb
app/views/cases/_form.html.erb

This PR reverts previous changes to make the datepicker default to the MM-DD-YYYY format.  For whatever reason, I am unable to change the format of the input data, so even if the date is inputted in the MM-DD-YYYY format, the app reads the data as DD-MM-YYYY.  Future changes to this form will change this field entirely.

Fix case date validation

---

app/helpers/analytics_helper.rb
app/helpers/application_helper.rb
app/helpers/cases_helper.rb
app/models/date_range.rb
app/views/cases/_thumbnail.html.erb
app/views/cases/show.html.erb
app/views/conversations/_conversation.html.erb
app/views/conversations/_messages.html.erb
config/initializers/time_formats.rb
spec/models/date_range_spec.rb

Adds initializer file to hold strftime formats and uses shorthand in views and models for clarity.   Also modifies the formats for readability (e.g., %d -> %e). Removes unused method from cases helper.

Adds initializer file to hold strftime formats

---

app/models/case.rb
db/migrate/20190824175709_add_cause_of_death_to_postgres.rb
db/migrate/20190825000337_rename_cause_of_death_for_cases.rb
db/structure.sql
lib/tasks/cases.rake
spec/lib/tasks/cases_rake_spec.rb

Adds migration to create cause of death enum.  Adds rake task to convert cause of death reference data on case table to enum.
Addresses Issue #3005 in part

Adds cause of death enum

---

app/controllers/cases_controller.rb
app/views/cases/_form.html.erb
config/locales/simple_form.en.yml

Changes case controller and form to use cause of death enum instead of model.
Addresses Issue #3005 in part.  Screenshot attached.

Changes case controller and form to use cause of death enum

---

Gemfile
Gemfile.lock
Rakefile

Updates devise to 4.7.1 for security vulnerability fix.  Adds ENV variable to suppress New Relic agent output on rake tasks - currently in production, the output of the new relic agent initialization is so verbose that any actual output of the task can't be seen.

Updates devise to 4.7.1 for security vulnerability fix

---

app/controllers/cases_controller.rb

Fix #3206: changed find method in case history action from `find_by_slug` to `find` and removed `this_case.blank?` from conditional statements.

Changed find method & removed conditional statement

---

app/views/cases/_form.html.erb

Disables include blank option for cause of death dropdown so selection is always displayed.

Disables include blank option for cause of death dropdown

---

README.md
app/controllers/application_controller.rb
app/helpers/user_notifier_helper.rb
app/jobs/application_job.rb
app/mailers/user_notifier.rb
app/services/sort_collection_ordinally.rb
config/environments/production.rb
config/environments/staging.rb
config/initializers/devise.rb
config/initializers/ranged_datetime_wrapper.rb
config/initializers/redis.rb
config/initializers/simple_form_bootstrap.rb
config/locales/en.yml
spec/helpers/user_notifier_helper_spec.rb
spec/mailers/admin_mailer_spec.rb
spec/mailers/previews/admin_mailer_preview.rb
spec/mailers/user_notifier_spec.rb
spec/models/agency_spec.rb
spec/models/case_spec.rb
spec/presenters/search_presenter_spec.rb
spec/support/controller_macros.rb
spec/support/shared_contexts/rake.rb

PR to address #3204 for Hacktoberfest and to remove rubocop warnings about long lines.
- Most use I18n or parameter line breaks
- Some other cases use escaped newlines or do-end blocks
- Some needed more than one technique or just a few characters removed
- I've broken the commits up by technique where possible
- A few other rubocop and whitespace fixes thrown in for free :laughing: 

Remove all rubocop long line warnings #3204

---

app/controllers/application_controller.rb

Prepends protect_from_forgery to before_action chain in application controller to fix csrf token bug

Fixes csrf token bug in Chrome

---

config/environments/production.rb

If we want to include links in emails, then we need to specify the host for ActionView to use.  We can do that in production by setting the default host option for URLs.

Adds default host option for production environment

---

db/structure.sql

https://github.com/EBWiki/EBWiki/commit/603d8af7356a38e4d1544bec85f93e4f5561791d introduced some git conflict artifacts to db/structure.sql, which broke `rake db:setup` (and, presumably, other db setup tasks.) 
Removing the conflict artifacts allows db setup to proceed.

Fix first-time database setup

---

config/environments/production.rb
config/environments/staging.rb

Cloudflare handles the SSL Configuration, I simply added a comment to explain this for anyone looking at the configuration files.
Addresses https://github.com/EBWiki/EBWiki/issues/1268
- [-] ~Include screenshots of any changes to the UI?~
- [-] ~Isolate any changes to gems (meaning that any new, updated, or removed gems and resulting code changes should be in their own PR)?~
- [-] ~Add and/or update specs for your code?~

Explain why force_ssl setting should remain disabled

---

app/policies/agency_policy.rb
spec/policies/agency_policy_spec.rb

Adds agency policy for `destroy` on `agency` to fix #3388 with spec
Issue reported in https://github.com/EBWiki/EBWiki/issues/3388
No UI changes required.

[FIX] Add agency policy for destroy action

---

app/mailers/user_mailer.rb
app/models/user.rb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/user_notifier/send_confirmation_email.html.erb
config/initializers/devise.rb
config/locales/en.yml
db/migrate/20191012043517_add_unconfirmed_email_to_users.rb
db/structure.sql
spec/mailers/devise_mailer_spec.rb
spec/mailers/previews/devise_mailer_preview.rb
spec/mailers/user_mailer_spec.rb

Per #3293, use Devise's `confirmable` module to confirm user emails.
* Remove our home-rolled `UserMailer.send_confirmation_email`
* Add :confirmable to User
* Add `unconfirmed_email` column to `users`, per Devise's demands
* Add tests on the confirmation email
* Preview the mailer at http://localhost:3000/rails/mailers/devise_mailer

Use Devise to confirm user emails

---

spec/mailers/devise_mailer_spec.rb

This PR fixes an issue with the mailer spec where it failed to decode text properly when a name included a symbol like an apostraphe.

Updates mailer spec to account for user names with symbols

---

.github/workflows/dockerhub.yml

This PR removes the tag using GITHUB_SHA when the newly built image is pushed to docker hub.

Remove tagging with GITHUB_SHA

---

Gemfile
Gemfile.lock

Update webmock gem from 3.5.1 to 3.9.1 version
closes #3779

Update webmock gem to 3.9.1 version

---

app/assets/config/manifest.js
config/initializers/assets.rb

**What**
* Introduce `app/assets/config/manifest.js`. Sprockets was [recently
upgraded][upgrade] to version 4, but [it now requires this file][file]
to exist in order to determine which files to compile.
* Disable concurrent exports for Sprockets. It has a tendency to [cause
segfaults][segfault] in Ruby, making builds (and deploys) super flaky.
I've already seen it fail a few times working on getting the build
passing.
[upgrade]: https://github.com/EBWiki/EBWiki/pull/3797
[file]: https://github.com/rails/sprockets/blob/master/UPGRADING.md#manifestjs
[segfault]: https://github.com/sass/sassc-ruby/issues/207

CI: fix Sprockets issues

---

.github/workflows/rubocop.yml

**What**
Update the CI configuration for Rubocop to install the same version that
is specified in `Gemfile.lock`. I think it might be better to run
`bundle` instead of installing `rubocop` directly, but it will be good
to set up caching to reduce performance overhead.

CI: specify rubocop version for build

---

config/environments/production.rb
config/environments/staging.rb

Updates the configuration of i18n fallbacks ahead of breaking change in ruby-18n. https://github.com/ruby-i18n/i18n/releases/tag/v1.1.0

Updates i18n fallback configuration

---

Gemfile
Gemfile.lock
db/seeds.rb
docs/DEVELOPMENT.md

Fixes the seeds file and removes the production database backup.  Updates the docs accordingly.  Also downgrades Sprockets due to seg fault issues.
More detail: Since the seeds file is in better shape, I went ahead and removed the production database backup.  We can find another spot for that, but I wasn't a huge fan of having that in the repo, since we could potentially expose personal information to anyone that clones the repo.  To that end, I included a note that if someone does need something closer to the prod database to work on a ticket to let us know.
I also downgraded Sprockets from 4 to 3.7.2 - Sprockets 4 is causing consistent segfaults when run on Linux distros with a kernel version of 5+, [as described here](https://github.com/rails/sprockets/issues/633).  Once that issue is …

Fixes seeds file and downgrades sprockets

---

Rakefile
spec/features/user_creates_agency_spec.rb
spec/requests/cases_spec.rb

Removes rubocop from Rakefile, which in turns removes the rubocop rake task - this is an attempt to address a LoadError for rubocop during Heroku deploys.

Removes rubocop from Rakefile

---

Gemfile
Gemfile.lock
config/initializers/carrier_wave.rb
spec/models/case_spec.rb
spec/rails_helper.rb

Changes `fog` gem to `fog-aws` for use of S3 with Carrierwave.  Also includes updates of specs for versioning functionality for cases.  Addresses #3789 

3789 change fog to fog aws

---

app/controllers/cases_controller.rb
app/models/case.rb
app/views/cases/_form.html.erb
app/views/cases/show.html.erb
config/locales/simple_form.en.yml
db/migrate/20220109194513_rename_cause_of_death_name_column.rb
db/migrate/20220109195551_remove_cause_of_death_id_from_cases.rb
db/structure.sql
spec/requests/conversations_spec.rb

Renames all instances of cause_of_death_name to cause_of_death.  Also removes unneeded cause_of_death_id column from cases table.  Addresses issue #4067 

Renames cause_of_death_name to cause_of_death
