EBWiki/EBWiki

Gemfile, Gemfile.lock, app/assets/javascripts/ahoy.js, app/assets/javascripts/application.js, app/assets/javascripts/comments.coffee, app/assets/javascripts/conversations.coffee, app/assets/javascripts/follows.coffee, app/assets/javascripts/mailbox.coffee, app/assets/javascripts/popover.js, app/assets/javascripts/select.js, app/assets/javascripts/tooltip.js, app/assets/javascripts/users.coffee, app/views/layouts/application.html.erb
I added the jquery.turbolinks gem so that javascript(including select2) properly loads.
Also moved most of the javascript to the asset pipeline (except for google analytics and google maps).
=> Jquery.turbolinks and put javascript in assets pipeline

app/views/articles/_form.html.erb
addressing Issue #120 . Still need view test for this.
=> adding explanatory tooltips to the article form partial

config/sitemap.rb
responsive to Google searches.
=> Adding followers pages to sitemap.  Will add more pages potentially

Gemfile, Gemfile.lock, app/controllers/concerns/case_filtering.rb, app/views/articles/index.html.erb, app/views/layouts/_ab_test.html.erb, config/initializers/split.rb, config/routes.rb
Adding split gem
Adding test of the color of the view maps button on the index page
Currently, test resets after completion instead of showing a given user
a consistent view, so we may want to change that. Also, Need to organize future tests with a new ruby object class as outlined here:
https://davidtuite.com/posts/a-b-testing-with-split-in-ruby-on-rails
=> Adding a simple button color test for split gem to work

app/controllers/concerns/case_filtering.rb, app/views/maps/index.html.erb
Moving test finish from case_filtering controller/concern to maps/index
view seems to do the trick
=> Refactoring Split test finish #378

app/mailers/user_notifier.rb
to include the title of the article
=> for issue #444 editing email subject

app/models/article.rb, spec/models/article_spec.rb
also added rspec to test that a version is created when any field is
updated
=> for issue #465 adjusting paper_trail to version all changes

app/models/article.rb, spec/models/article_spec.rb
=> Revert "for issue #465 adjusting paper_trail to version all changes"

app/models/article.rb, spec/models/article_spec.rb
so the pull request will work vs master
=> redoing the changes for #465 in a new branch

app/models/article.rb, spec/models/article_spec.rb
=> for #472 adding validation that article date is in the past

Gemfile, Gemfile.lock, app/models/user.rb, app/views/articles/index.html.erb, config/initializers/gibbon.rb
Small change to make sure that the newsletter button does not show up
for users who have already subscribed. Necessitated adding some model
methods to return mailchimp status and updating the gem to v2.1
=> For issue #469 adding newsletter conditional

app/views/user_notifier/send_followers_email.html.erb, config/environments/development.rb
This change will add a little more content to messages to followers.
=> For #578 adding commit summary to update message

config/sitemap.rb
fixing config setting to make default host reference the https: root
instead of merely http:
=> for #836 changing to ssl in sitemap

Gemfile, Gemfile.lock, app/controllers/agencies_controller.rb, app/models/agency.rb, app/views/agencies/_form.html.erb, app/views/agencies/show.html.erb, app/views/articles/_form.html.erb, db/migrate/20170520020651_add_jurisdiction_to_agencies.rb, db/schema.rb
Issue resolution and refactoring.
Added a 'jurisdiction' field to the Agency model in order to fill the function of #738 . It shows as a dropdown in the form. (Calling it 'Type' gave me errors, see #903 ) 
Should this field be labelled "type", "jurisdiction", or something else in the view?
Other issues addressed: #907 ,  #853 ,  #901 .
=> Agency Workflow

README.md, config/environments/test.rb, spec/rails_helper.rb
Configures Bullet to run for each test, both in a local testing environment as well as in Travis when pull requests are opened.
=> Adds automatic check via bullet to test environment.

app/mailers/user_notifier.rb, spec/mailers/user_notifier_spec.rb
=> Removes method send_update_email.

README.md
=> Update Ruby, and Rails version.

app/assets/stylesheets/application.scss
=> issue #959: added space between related cases and map

app/assets/stylesheets/application.scss, app/assets/stylesheets/articles.scss, app/assets/stylesheets/forms.scss
Fixed the width of the sidebar elements on the articles page, and added space between the comment input section and submit button.
=> Article sidebar width fixes

db/seeds.rb
Adds users and articles to seed file.  Addresses issue #1003.
=> Adds users and articles to seed file.

README.md
Mostly so that I can pass along the previously merged PRs so they can pass properly.  Also rewords a phrase in the README.
=> Rewords phrase in readme.

app/assets/stylesheets/application.scss
=> Revert "issue #959: added space between related cases and map"

app/assets/stylesheets/articles.scss
Replicates end result of reverted PR #1068
=> Adds spacing between map and related cases on article page.

README.md
=> Adds label info and thank you note to README.

app/views/agencies/show.html.erb
Refactors logic in the agencies show page to use the pluralize helper.
=> Refactors logic using pluralize helper in agencies show page.

app/helpers/agencies_helper.rb, app/views/agencies/index.html.erb, db/schema.rb, db/seeds.rb
Updates the seed file to create agencies.  Also removes logic from the agencies index view and instead creates functions within `app/helpers/agencies_helper.rb`.
This PR directly addresses issues #1110 and #915.
=> Updates seeds file and removes logic from agencies index view

app/controllers/analytics_controller.rb, app/models/article.rb, app/models/visit.rb, app/views/analytics/_top_metrics.html.erb
This PR moves logic out of the analytics top metrics partial.  Instead, some of the queries performed are added as scopes on the corresponding models and passed as instance variables from the controller.  There is also some slight refactoring of the analytics controller to make the code more readable and idiomatic.
This PR addresses issue #917
=> Moves logic out of analytics top metrics partial.

spec/factories/agencies.rb, spec/helpers/agencies_helper_spec.rb
=> Adds spec for agency helper methods.

spec/factories/state.rb, spec/models/agency_spec.rb, spec/support/geocoder.rb
This PR adds specs to cover agency scopes.
=> Adds specs for agency scopes.

Gemfile, Gemfile.lock
This PR contains an updated Gemfile to install and use the latest stable version of Faker.
=> Updates faker gem

app/models/article.rb, spec/models/article_spec.rb
Makes change from Date.today to Date.current and adds scope for finding articles by state.
=> Minor fixes

app/controllers/articles_controller.rb, app/views/articles/_form.html.erb, app/views/articles/followers.html.erb
Refactors the articles form partial by performing database queries in the corresponding controller action.  Also refactors the articles followers page by using the `pluralize` helper where appropriate.
Addresses issue #919 and part of #920.
=> Refactors logic in articles form partial and followers view.

spec/fixtures/ethnicities.yml
This pr creates ethinicities fixtures to be used for tests
=> Create ethnicities fixture fixes #1338

app/assets/stylesheets/forms.scss
=> Remove weird dots undernearh star on required fields in forms

config/locales/views/ethnicities/en.yml, config/locales/views/states/en.yml
This pr creates a locale ethnicitity file and creates the ethinicies in alphabetical order.
It also creates locale state and creates all the cities in alphabetical order
=> create ethnicity locale file solves#1391 and #1390

Gemfile.lock
=> Update loofah gem fixes #1389

app/views/users/show.html.erb, spec/features/user_visits_user_profile_page_spec.rb
- app/views/users/show.html.erb - Changed article to following_case
- spec/features/user_visits_user_profile_page_spec.rb - Added specs
for the user visiing the user history page.
Updates #1422
- [ X ] Include a description of the changes?
- [ X ] Mention the issue the PR addresses?
- [ X ] Add and/or update specs for your code?
=> Fixed Article variable issue in user page

README.md, docs/DEVELOPMENT.md
=> local setup link changed

app/helpers/user_notifier_helper.rb, app/mailers/user_notifier.rb, app/views/user_notifier/welcome_email.html.erb, spec/helpers/user_notifier_helper_spec.rb, spec/mailers/user_notifier_spec.rb
Refactors welcome email by moving logic to helper.  Addresses issue #927 
=> Refactors welcome email

Gemfile, Gemfile.lock, config/routes.rb, spec/controllers/cases_controller_spec.rb, spec/requests/articles_redirect_spec.rb
- Gemfile - Updated paper_trail version to 4.2.0
- Gemfile.lock - Locked version of the file
- config/routes.rb - Added routes to redirect /article links to /case
- spec/requests/articles_redirect_spec.rb - Specs to confirm that the
article redirect is in place.
Updates #1437
=> Redirect /article to /case

spec/models/case_spec.rb
This PR updates `case_spec.rb` to account for time zone difference when testing that the version changes if the date is changed.
=> Changes spec for version updates to account for time zones.

Gemfile, Gemfile.lock
- Gemfile - set searchkick to version '~> 2`
- Gemfile.lock - Lock version of files
Updates #1519
=> Pinned searchkick gem to 2.x to avoid upgrade issues

app/assets/javascripts/select.js, app/assets/stylesheets/analytics.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/forms.scss, app/views/cases/_form.html.erb, app/views/cases/followers.html.erb, app/views/cases/index.html.erb, app/views/cases/show.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb
=> 997 fix vertical header size

app/models/subject.rb, app/views/cases/show.html.erb
Refactors code in case show view to use pluralize helper for nearby cases section.  Updates subject model to have association with case instead of article.
=> Minor refactoring

lib/tasks/cases.rake
=> Uses update_attribute in add_blurb rake task to skip validations.

Gemfile.lock
Updates Sprockets to the next patch version, 3.7.2, to address security vulnerability.
=> Updates Sprockets to v3.7.2 to protect against vulnerability.

app/helpers/analytics_helper.rb, app/helpers/application_helper.rb, app/helpers/cases_helper.rb
- This pr refactors `link_to_case_title` that is present in both analytics and cases helper
- It solves issue #1651
=> refactor link_to_case_title solves  #1651

db/migrate/20180703071052_add_title_to_links.rb, db/schema.rb
This pr adds title attribute in the links table. It solves issue #1654
=> add title to links solves #1654

app/helpers/agencies_helper.rb, app/helpers/application_helper.rb, app/helpers/cases_helper.rb, app/views/agencies/index.html.erb, app/views/analytics/index.html.erb, app/views/cases/index.html.erb
- This pr refactors the updated_at method found in both agencies and cases helper and combines them into one generic method.
- It solves issue number #1652
=> Refactor the updated_at method in cases and agencies helper solves #1652

app/controllers/agencies_controller.rb, app/views/agencies/_form.html.erb, app/views/agencies/show.html.erb, spec/features/user_creates_agency_spec.rb
=> map data for jurisdiction values to jurisdiction_type enum #1621

app/controllers/cases_controller.rb, app/helpers/cases_helper.rb
=> replaced fuctionality in cases controller with helpers

Gemfile, Gemfile.lock
=> updated jquery-rails gem

app/assets/stylesheets/application.scss
=> add official colours as CSS variables

app/models/case.rb, app/models/link.rb, spec/controllers/cases_controller_spec.rb, spec/factories/cases.rb, spec/factories/links.rb, spec/models/case_spec.rb
This Pr validate url presence
- Solves issue  #1658
=> validate url presence solves#1658 

Gemfile, Gemfile.lock
- This pr updates gem bullet to version 5.7
- It also moves it to group development and test
- It solves #1708
=> update gem bullet and move it to group development and test solves#1708

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss
- This pr solves #1649 
- It adds gem full calendar to the Gemfile
=> add gem full calendar and its dependencies solves#1649

Gemfile, Gemfile.lock
This pr updates gem sitemap_generator
- Solves issues#1707
=> update gem sitemap_generator solves##1707

Gemfile, Gemfile.lock
This pr updates gem gotcha to the latest version, I have also included the build/patch number since the gem does not have any minor and major releases yet
- solves issue #1706
=> update gem gotcha soves#1706

Gemfile, Gemfile.lock
This pr updates gems fro charts which include:
- active_median
- chartkick
- groupdate
- hightop
It solves issue 1705
=> update gems for charts solves#1705

app/controllers/cases_controller.rb, app/helpers/cases_helper.rb, app/views/cases/_subject_fields.html.erb
This pr sorts gender using SortCollectionOrdinally.
solves  issue #1653
=> refactor drop down in cases controller solves#1653

app/views/static/contribution_guidelines.htm.erb
fixes #130
The new view contains content on guide to contributing to Wiki
=> Added new view under static_pages 

Gemfile, Gemfile.lock
This pr updates gem pre-commit
- solves iisue #1777
=> update gem pre-commit solves #1777

Gemfile, Gemfile.lock
This pr updates gem pry_byebug
-solves issue #1776
=> update gem pry_byebug solves #1776

app/controllers/cases_controller.rb, db/seeds.rb, spec/fixtures/ethnicities.yml
This pr adds Pacific Islander to ethnicities 
- solves #558
=> Add Pacific Islander to ethnicities solves #558

Gemfile, Gemfile.lock
this pr updates jquery-turbolinks gem to the latest version
fixes #1670
=> Update jquery-turbolinks gem

Gemfile, Gemfile.lock
=> Update sdoc gem

config/initializers/ahoy.rb, spec/models/agency_spec.rb, spec/models/case_spec.rb, spec/models/subject_spec.rb, spec/models/user_spec.rb
This pr refactors model tests to use shoulder matchers
=> Shoulder matchers #1646 

Gemfile, Gemfile.lock
Added JSON renderer for Rails gem, jb gem 
fixes #1650
=> Add jb gem

Gemfile, Gemfile.lock, config/initializers/ahoy.rb
This pr updates gem split
- solves issue #1766
=> update gem split solves #1766

Gemfile.lock, app/views/agencies/show.html.erb, config/initializers/ahoy.rb
This pr removes the conditional check on  if the jurisdiction is present since there is a similar method in the helper.
- Solves issue #1622
=> refactor agency show page solves #1622

Gemfile, Gemfile.lock
=> Update factory_bot_rails gem

Gemfile, Gemfile.lock
=> update simplecov gem to 0.16.1'

Gemfile, Gemfile.lock
- Update gem rollbar
- Solves issue #1767
=> update gem rollbar#1767

Gemfile, Gemfile.lock, app/controllers/application_controller.rb
- Update to  4.0.0.rc1
- solves #1729
=> Update devise to 4.0.0.rc1 #1729

Gemfile, Gemfile.lock
=> Update brakeman gem

Gemfile, Gemfile.lock
This pr updates gem guard_rspec
- Solves issue #1775
=> update gem guard rspec#1775

Gemfile, Gemfile.lock
- Update Gem faker 
- Solves issue #1811
=> update gem faker solves#1811

Gemfile, Gemfile.lock
This pr updates gem Capybra
- Solves issue #1808
=> Update gem capybara solves #1808

Gemfile, Gemfile.lock
=> update cucumber-rails gem

Gemfile, Gemfile.lock
=> Update launchy gem

Gemfile, Gemfile.lock
This pr Update gmaps4rails gem
- Solves #1864
=> Update gmaps4rails gem #1864

Gemfile, Gemfile.lock
- This pr Update rack-host-redirect gem 
- Solves #1879
=> Update rack-host-redirect gem #1879

Gemfile, Gemfile.lock
This pr Update httparty gem
- Solves  #1878
=> Update httparty gem #1878

Gemfile, Gemfile.lock
Update newrelic_rpm gem
-solves #1877
=> Update newrelic_rpm gem #1877

Gemfile, Gemfile.lock
Update ckeditor gem 
- Solves #1876
=> Update ckeditor gem #1876

Gemfile, Gemfile.lock
Update galerts gem 
- Solves #1875
=> Update galerts gem #1875

Gemfile, Gemfile.lock
=> update database_cleaner gem

Gemfile, Gemfile.lock
=> Update bootstrap-sass gem

Gemfile, Gemfile.lock
=> Update rails_admin gem #1862

Gemfile, Gemfile.lock
Update heroku_rails_deflate gem 
- Solves #1861
=> Update heroku_rails_deflate gem #1861

Gemfile, Gemfile.lock
Update carrierwave-imageoptimizer gem
- Solves  #1860
=> Update carrierwave-imageoptimizer gem #1860

Gemfile, Gemfile.lock
Update mini_magick gem 
- Solves #1858
=> Update mini_magick gem #1858

Gemfile, Gemfile.lock
Update simple_form gem
- Solves  #1856
=> Update simple_form gem #1856

Gemfile, Gemfile.lock
Update bootstrap3-datetimepicker-rails gem 
- Solves #1854
=> Update bootstrap3-datetimepicker-rails gem #1854

Gemfile, Gemfile.lock
=> #1865 updated puma gem to version ~> 3.12

Gemfile, Gemfile.lock
Update carrierwave gem 
- Solves #1859
=> Update carrierwave gem #1859

Gemfile, Gemfile.lock
Update rails12_factor gem 
- Solves #1855
=> Update rails12_factor gem #1855

Gemfile, Gemfile.lock
=>  #1866 updated searchkick gem to version ~> 3.1

Gemfile, Gemfile.lock
=> updated mailboxer gem to version ~> 0.14

app/assets/stylesheets/agencies.scss, app/assets/stylesheets/cases.scss, app/assets/stylesheets/users.scss, app/views/agencies/_form.html.erb, app/views/agencies/new.html.erb, app/views/cases/_form.html.erb, app/views/cases/edit.html.erb, app/views/cases/new.html.erb, app/views/users/_form.html.erb, app/views/users/edit.html.erb
=> Replacing "back" link on pages with button

app/controllers/users/registrations_controller.rb, spec/features/user_visits_case_history_spec.rb
Refactor user registration controller 
- Solves #1840
=> Refactor user registration controller #1840

Gemfile, Gemfile.lock
Update gem devise 
- solves#1733
=> Update gem devise solves#1733

app/controllers/application_controller.rb
Redirect back to current page after sign in, sign out, sign up, update 
- solves#1764
=> Redirect back to current page after sign in, sign out, sign up, update solves#1764

app/controllers/messages_controller.rb
=> add strong param in message controller

app/assets/javascripts/popover.js
- app/assets/javascripts/popover.js - Added a trigger hover event
to the popover so that the popover disappears when the mouse leaves
the element
Updates #721
=> Changed popover trigger event to hover

app/controllers/cases_controller.rb
This pr comments out the link part on the flash message
-Solves #1890
=> Comment out part the flash with link solves #1890

app/controllers/agencies_controller.rb
This Pr enables proper redirects in agencies controller after sign in and sign up
- Solves #2043
=> Add redirect to agencies controller Solves#2043

app/controllers/agencies_controller.rb, app/controllers/comments_controller.rb
=>  #2045 Changed filter callbacks in CommentsController and AgenciesController

app/controllers/users_controller.rb
=> #2035 Added redirects for user controller

spec/models/user_spec.rb
This pr tests that one cannot sign in with an existing email
solves # 80
=> Test email uniqueness  solves #80

app/controllers/organizations_controller.rb
=> #2037 Added redirects for organizations controller

app/controllers/maps_controller.rb
=>  #2038 Added redirects for maps controller

app/controllers/comments_controller.rb
=> #2039 Added redirects for comments controller

app/models/case.rb, spec/models/case_spec.rb
=> #1889 Removed presence requirement for links in case model

app/controllers/conversations_controller.rb
=> #2041 Added redirects to conversations controller

app/controllers/mailbox_controller.rb
=> #2040 Added redirects for mailbox controller

app/controllers/cases_controller.rb
=> #2042 Added redirects to cases controller

Gemfile, Gemfile.lock
- Removed  rspec-activemodel-mocks gem
- Solved #1797.
=> removed_activeModel

spec/models/case_spec.rb
-Combined describe blocks.
-Solved issue #1980
=> Combined describe blocks

app/controllers/users/registrations_controller.rb, spec/mailers/user_notifier_spec.rb
Move code changes to registrations controller 
Solves #2070
=> Move code changes to registrations controller #2070

app/views/comments/_add_comment_form.html.erb
Fixes #2100 removed  disable_with from comments form
=> remove disable_with in comments form

.gitignore, app/controllers/follows_controller.rb
=> for #2114 updated follows controller to use friendly

docs/SETUP_LOCALLY.md
=> for #2147 removed the line < < < < < HEAD from SETUP_LOCALLY.md

app/views/cases/history.html.erb, spec/features/user_visits_case_history_spec.rb
=> #2161 Changed whodunnit lookup for history page

app/controllers/cases_controller.rb, app/views/comments/_add_comment_form.html.erb, app/views/comments/index.html.erb
=> #2110 removed @commentable instance in the show action

app/controllers/agencies_controller.rb
change string to symbol in before action 
- Solves #2267
=> change string to symbol in before action #2267

app/controllers/agencies_controller.rb
Made the methods after_sign_up_path and after_sign_in_path in agencies controller to be private
=> #2274 moved after_sign_up_path and after_sign_in_path methods to private

config/routes.rb
=> Remove dynamic action from routes

spec/factories/cases.rb, spec/factories/comments.rb, spec/factories/conversations.rb, spec/factories/ethnicities.rb, spec/factories/event_statuses.rb, spec/factories/genders.rb, spec/factories/organizations.rb, spec/factories/states.rb, spec/factories/users.rb, spec/factories/visits.rb
Wrap all values in blocks in factories 
- Solves #2227
=> Wrap all values in blocks in factories #2227

app/controllers/cases_controller.rb, spec/controllers/cases_controller_spec.rb
=> set instance variable in cases controller action

app/models/link.rb
=> #2320 removed the belongs_to association for case in the link model

Gemfile, Gemfile.lock
=> # 2312 updated rspec-rails gem to version ~> 3.8

app/null_objects/guest.rb, spec/null_objects/guest_spec.rb
closes #2275 
Add NullObjects::Guest class
=> #2275 Add NullObjects::Guest class

app/views/cases/history.html.erb
=> #2233 updated cases history page

app/helpers/cases_helper.rb, app/views/cases/show.html.erb
=> #2321 refactored the video url helper in show view of cases

app/controllers/organizations_controller.rb
=> set instance variable in organizations controller action

app/controllers/agencies_controller.rb
added status: :created to be returned when an agency is successfully created.
=> #2313 added a :created status on successful save

app/helpers/cases_helper.rb, spec/helpers/cases_helper_spec.rb
Remove case_sanity_check helper 
- Solves #2379
=> Remove case_sanity_check helper #2379

app/views/layouts/application.html.erb
Update application layout to account for undo and redo links 
- Solves #1895
=> Update application layout to account for undo and redo links #1895[wip]

app/views/cases/_main_content.html.erb
Remove presence check from case show partial 
- Solves #2392
=> Remove presence check from case show partial #2392

app/controllers/cases_controller.rb
closes #2377 
Eager load comments & subjects in the case show action
=> #2377 Eager load comments & subjects in case show action

app/controllers/cases_controller.rb, app/views/cases/_main_content.html.erb
closes #2376 
Remove presence check from CasesController show action
=> #2376 Remove presence check from Cases show action

app/controllers/agencies_controller.rb
=> #2094 removed respond_to blocks in agencies controller

app/models/case.rb
Remove unused validation for empty fields for cases 
- Solves #2418
=> Remove unused validation for empty fields for cases #2418

config/initializers/ahoy.rb
Add settings to ahoy initializer 
- Solves #2417
=> Add settings to ahoy initializer #2417

app/helpers/cases_helper.rb
-Removed make_undo_link and make_redo_link helpers.
-Solved issue #1896
=> Removed make_undo_link and make_redo_link helpers

app/controllers/cases_controller.rb, app/views/cases/_subject_fields.html.erb
closes #2436 
Move Ethnicity model query from view partial to CasesController
=> #2436 Move Ethnicity model query from view partial to CasesController

.gitignore, config/database.example.yml, docs/SETUP_LOCALLY.md
=> #2322 Created example database config file

app/assets/stylesheets/users.scss, app/views/users/show.html.erb
=> #2429 Added last seen at and change button colors on user profile page

app/views/cases/history.html.erb
=> #2430 Removed last seen at field from history page

app/models/ethnicity.rb
Enable friendly-id for ethnicities #1442
=> Enable friendly-id for ethnicities #1442

app/assets/stylesheets/agencies.scss, app/assets/stylesheets/bootstrap-mods.scss, app/views/agencies/_form.html.erb, app/views/agencies/edit.html.erb, app/views/agencies/new.html.erb
=> #2435 Moved buttons to agency form partial 

app/views/cases/edit.html.erb, spec/features/editor_edits_case_spec.rb
=> #2457 updated the meta description and header of the edit case view

db/migrate/20180926091204_validate_name_presence_on_users.rb, db/structure.sql
Add database constraint for users and name 
Solves #2449
=> Add database constraint for users and name #2449

app/assets/stylesheets/cases.scss, app/views/cases/show.html.erb
=> #2468 Updated HTML class name from articleTitle to case-title

db/migrate/20180926092536_validate_overview_presence_on_cases.rb, db/structure.sql
Add database constraint for cases and overview 
Solves #2448
=> Add database constraint for cases and overview #2448

app/assets/stylesheets/cases.scss, app/views/cases/_form.html.erb, app/views/cases/_link_fields.html.erb, app/views/cases/_subject_fields.html.erb, app/views/cases/edit.html.erb, app/views/cases/new.html.erb
=> #2467 moved back button to  case form partial

db/migrate/20180926123043_validate_title_presence_on_cases.rb, db/structure.sql
=> Add database contraint for cases and title

app/views/cases/index.html.erb, app/views/layouts/_header.html.erb
=> Move getnewsletter button to the header

app/views/cases/index.html.erb, app/views/layouts/_header.html.erb
=> Revert "Move getnewsletter button to the header"

app/controllers/cases_controller.rb, db/migrate/20181001124317_edit_summary_on_cases.rb, db/structure.sql, spec/controllers/cases_controller_spec.rb, spec/factories/cases.rb, spec/lib/null_fields_counter_spec.rb
Prevent cases from saving without a summary #2452
=> Prevent cases from saving without a summary #2452

Gemfile, Gemfile.lock, db/migrate/20181005060647_add_sessions_table.rb, db/structure.sql
=> Changes cookie store to activerecord_session_storage

Gemfile, Gemfile.lock
=> [Issue #2473] Update Sitemap Generator Gem

app/models/gender.rb, db/migrate/20181008175901_add_slug_to_genders.rb, db/structure.sql
=> Enable friendly-id for genders #1441

spec/fixtures/categories.yml
=> Create fixture file for categories #1444

app/controllers/application_controller.rb, app/policies/application_policy.rb
Description: Setup Pundit https://github.com/EBWiki/EBWiki/issues/2524
=> Setup pundit #2524

.env.example, config/routes.rb
- Resolves: https://github.com/EBWiki/EBWiki/issues/2494
- #2494 
=> [#2494] Use env variable for sitemap route

app/models/case.rb
=> [Issue #2428] Return empty array if none exist for nearby_cases

Gemfile, Gemfile.lock
=> Adds therubyracer gem

app/views/mailboxer/message_mailer/reply_message_email.html.erb, app/views/mailboxer/notification_mailer/new_notification_email.html.erb
=> Remove raw method from email templates #2547

Gemfile, Gemfile.lock, app/models/calendar_event.rb, app/models/calender_event.rb, config/initializers/rails_admin.rb, config/routes.rb, db/structure.sql
=> Fix routing error

app/controllers/agencies_controller.rb, app/controllers/application_controller.rb, app/controllers/cases_controller.rb, app/services/sort_collection_ordinally.rb, app/views/agencies/_form.html.erb, spec/features/user_creates_agency_spec.rb, spec/services/sort_collection_ordinally_spec.rb, spec/views/cases/index.html.erb_spec.rb, spec/views/cases/show.html.erb_spec.rb
Add optional attribute name parameter to sorting service object 
- Solves #1981
=> Add optional attribute name parameter to sorting service object #1981

app/views/static/about.html.erb, db/structure.sql
Add Washington Post to list of admired sites on about page
- Solves #2540
=> Add Washington Post to list of admired sites on about page #2540

app/controllers/users_controller.rb, app/policies/user_policy.rb, spec/policies/user_policy_spec.rb, spec/rails_helper.rb
Add a policy for users 
- Solves #2552
=> Add a policy for users #2552

app/models/link.rb, app/views/cases/history.html.erb, spec/models/case_spec.rb
Update case when link is updated #2263
=> Update case when link is updated #2263

db/migrate/20181025082828_validate_name_uniqueness_on_agencies.rb, db/structure.sql
Add database constraint for unique names for agencies 
- Solves #2445
=> Add database constraint for unique names for agencies #2445

Gemfile, Gemfile.lock, config/initializers/paper_trail.rb, db/structure.sql
Migrations were not added since `20170520020651_init_schema.rb` already has the required changes to support the gem.
=> Install paper_trail association gem #2550

app/controllers/application_controller.rb
The two unused methods `mailbox` and `conversations` are to be removed in the application_controller.rb
The unused methods have been successfully removed.
=> Remove methods

config/routes.rb
=> Update map routes #2493

db/migrate/20181026005352_add_confirmable_to_devise.rb, db/structure.sql
This migration will make prepare the users model for confirmable users with Devise: https://github.com/EBWiki/EBWiki/issues/2631
The migration now reflects the exact one listed in the issue rather than editing it to reflect the guides 👍
- [√] Include a description of the changes?
- [√] Mention the issue the PR addresses?
=> Migration to Make Users Confirmable with Devise

app/controllers/users/registrations_controller.rb
=> Removed commented out code for issue #2701

app/models/agency.rb, app/models/case.rb, app/models/follow.rb, app/models/visit.rb
the pr aims to reduces some of the rubocop issues as discusses on #2679
=> Fix some of the rubocop issues

app/assets/stylesheets/cases.scss, app/views/cases/_form.html.erb, app/views/cases/_link_fields.html.erb
=> #2677 Add newline between link fields on case form

spec/factories/users.rb
Remove DEPRECATION WARNING in factories/users #2617
=> Remove DEPRECATION WARNING in factories/users #2617

app/controllers/cases_controller.rb, app/views/cases/_button_group.html.erb, spec/features/user_follows_case_spec.rb
=> Makes feature specs for testing following and unfollowing functionality more idiomatic.

db/migrate/20190112221750_add_name_index_to_states.rb, db/migrate/20190112222534_add_started_at_index_to_visits.rb, db/migrate/20190112223009_add_created_at_index_to_users.rb, db/migrate/20190112223318_add_name_index_to_ahoy_events.rb, db/migrate/20190112223645_add_admin_index_to_users.rb, db/migrate/20190112224118_add_title_index_to_cases.rb, db/migrate/20190112224451_add_ansi_code_index_to_states.rb, db/migrate/20190112224801_add_created_at_index_to_follows.rb, db/seeds.rb, db/structure.sql, spec/views/cases/index.html.erb_spec.rb, spec/views/maps/index.html.erb_spec.rb
=> Adds database indexs for queries.  Minor refactoring.

app/uploaders/avatar_uploader.rb, spec/features/user_visits_home_page_spec.rb, spec/features/user_visits_user_profile_page_spec.rb
=> Adds default url for case avatars.

app/assets/stylesheets/cases.scss, app/views/cases/index.html.erb
Will merge immediately after tests pass because you know, hotfix.
=> Fixes alignment issue on homepage.

config/initializers/session_store.rb
Please note that this will be deployed to prod during off-hours since the app will need to be restarted.
=> Changes session store from cookie store to database

.gitignore, app/views/cases/index.html.erb, db/seeds.rb, db/structure.sql
[#2799](https://github.com/EBWiki/EBWiki/issues/2799)
_There's no change on the UI as shown below_
N/A
N/A
=> #2799 Remove unnecessary `count` query in homepage 

app/views/layouts/application.html.erb
In full, there is no need to use html_safe when displaying flash messages, as all messages are generated by the code and not a user.
=> Removes unnecessary usage of html_safe and fixes indentation in application layout

Gemfile, Gemfile.lock
=> Upgrades devise for security patches

db/migrate/20190323221344_remove_jurisdiction_from_agencies.rb, db/structure.sql
Removes the jurisdiction enum.  I'll add it back with proper names once this has been merged.
=> Removes broken jurisdiction enum from agencies.

Gemfile, Gemfile.lock, app/models/agency.rb, app/models/case.rb, app/models/comment.rb, app/models/follow.rb, app/models/subject.rb, app/models/user.rb, spec/models/agency_spec.rb, spec/models/case_spec.rb, spec/models/comment_spec.rb, spec/models/follow_spec.rb, spec/models/subject_spec.rb, spec/models/user_spec.rb, spec/models/visit_spec.rb, spec/support/shared_examples/sanatized_record_spec.rb
Add auto_strip_attributes gem
Remove type from model specs since,  config.infer_spec_type_from_file_location! is configured
Add shared_example spec for stripping white spaces
=> Implement automatically stripping of attributes

app/controllers/analytics_controller.rb, app/models/date_range.rb, app/models/thirty_day_period.rb, app/models/user.rb, app/views/users/show.html.erb, db/migrate/20190406032344_add_jurisdiction_to_postgres.rb, db/structure.sql, lib/statistics.rb, spec/lib/statistics_spec.rb, spec/models/date_range_spec.rb
Fix formatting in html file
- Solves  #2864
=> Fix formatting in html file

app/controllers/cases_controller.rb, app/models/case.rb, app/models/category.rb, app/models/cause_of_death.rb, app/views/cases/_form.html.erb, config/initializers/inflections.rb, db/migrate/20190422003442_migrate_category_fields_to_cause_of_death.rb, db/structure.sql, spec/controllers/cases_controller_spec.rb, spec/factories/states.rb
This PR addresses #2956, which is converting the category model to cause of death.  This also includes a minor change to the state factory.
=> Redo categories

app/views/analytics/_blockquote_comments.html.erb, app/views/analytics/_followed_cases.html.erb, app/views/analytics/_updated_cases.html.erb, app/views/analytics/_visited_cases.html.erb, app/views/analytics/index.html.erb
Renders tables for cases and comments as collections to improve performance.
=> Renders parts of analytics page using collections and partials.

app/controllers/analytics_controller.rb, app/views/analytics/_top_metrics.html.erb, app/views/analytics/index.html.erb, lib/statistics.rb, spec/lib/statistics_spec.rb
Change mom to increase
- Solves #2957
=> Change mom to increase #2957

app/inputs/date_picker_input.rb, app/inputs/datetime_picker_input.rb
=> Change datepicker defaults to MM/DD/YYYY

app/views/search/show.html.erb
=> Centers search results on page.

app/controllers/cases_controller.rb, app/views/comments/index.html.erb
=> Bug fixes for syntax errors and missing instance variables.

app/assets/stylesheets/application.scss, app/assets/stylesheets/scaffolds.scss
This PR refactors duplicate `font-family` declarations in the codebase.
=> Put font-family at HTML tag level & removed duplicates #3058

Gemfile, Gemfile.lock
=> Updates mini_magick gem for security patch.

app/controllers/analytics_controller.rb
=> Get number of cases for new case updates in analytics chart.

app/controllers/agencies_controller.rb, app/models/agency.rb, app/views/agencies/_form.html.erb, app/views/agencies/show.html.erb, db/migrate/20190815012327_remove_agency_fields.rb, db/structure.sql
Removes the description and lead officer attributes in the agency model.
=> Remove agency fields

app/assets/stylesheets/application.scss, app/assets/stylesheets/scaffolds.scss, app/views/agencies/_form.html.erb, app/views/cases/_form.html.erb, app/views/cases/_info_window.html.erb, app/views/layouts/_header.html.erb
=> Remove styles from html (issue 3058)

Gemfile, Gemfile.lock, app/controllers/users/registrations_controller.rb, app/views/devise/registrations/new.html.erb, spec/requests/registrations_spec.rb
Removed gotcha from the user registration process because it doesn't work with Rails 5 and Devise. Provides a short term fix for 3168
=> Removed gotcha from user registration process #3168

.travis.yml
=> Added encrypted variables to build #3221

app/controllers/cases_controller.rb
Summary:
Removed an instance variable
Issue: https://github.com/EBWiki/EBWiki/issues/3207
=> Remove cause of death from instance variables

Gemfile, Gemfile.lock
Update the pg gem to the latest version #1664 
Reference: https://rubygems.org/gems/pg/versions/1.1.4
=> Update pg gem to 1.1.4

Gemfile, Gemfile.lock
This PR will resolve #3229 and upgrading simple_form to version 5.0.0
=> Updated the simple_form gem to version 5.0

lib/tasks/geocode_data.rake
=> Fix geocode:all task issue regarding summary text

app/mailers/user_notifier.rb, app/views/user_notifier/send_confirmation_email.html.erb, spec/mailers/user_notifier_spec.rb
Summary:
Added a new mailer for password confirmation.
The view file needs more copy and links.
Issue: [https://github.com/EBWiki/EBWiki/issues/3202](https://github.com/EBWiki/EBWiki/issues/3202)
=> Add a password confirmation mailer.

app/assets/stylesheets/application.scss, app/views/cases/index.html.erb
- Highlight content on the landing page.
- Solves #1096
=> change the number of people killed to be the orange

app/views/cases/index.html.erb, app/views/layouts/_header.html.erb
=> view: moves get newsletter button to navbar for better visibility

app/policies/case_policy.rb, spec/policies/case_policy_spec.rb
Added a case policy
Fixes #3382
=> Add case policy

Gemfile, Gemfile.lock, app/controllers/users/registrations_controller.rb, app/views/devise/registrations/new.html.erb
=> Working Recaptcha. Puts recaptcha on user sign up page[#3370]

app/views/cases/history.html.erb
In regards to issue **Add link to user in history tab #782**, replaced `<%= user.name %>` with
`<%= link_to user.name, user_path(user) %>` to link user's name to corresponding user page.
=> History page user link (Issue #782)

spec/factories/users.rb, spec/requests/follows_spec.rb
=> Adds confirmed_at field to user factory for testing.

app/mailers/case_mailer.rb, spec/mailers/devise_mailer_spec.rb, spec/requests/registrations_spec.rb
=> Added explicit send to reinforce sending mail #3472

app/views/cases/_form.html.erb
=> Makes the cause of death dropdown required in the case form

app/controllers/cases_controller.rb, app/views/cases/_form.html.erb
=> 3571 change sessions

README.md, docs/DEPLOYING.md, docs/DEVELOPMENT.md
=> 3593 update main

app/views/cases/index.html.erb, app/views/layouts/_header.html.erb
=> 3605 home page changes

app/assets/stylesheets/application.scss, app/views/cases/followers.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb, app/views/maps/index.html.erb, config/routes.rb
=> 3559 fix non transparent background

app/views/layouts/application.html.erb, app/views/maps/index.html.erb, config/routes.rb, spec/views/maps/index.html.erb_spec.rb
=> 3648 add here libraries to codebase

app/models/case.rb, app/views/cases/_form.html.erb, config/locales/simple_form.en.yml, db/migrate/20200901014746_add_stabbing_to_causes_of_death.rb
=> Added stabbing to cause_of_death #3644

.github/workflows/dockerhub.yml
=> GitHub actions dockerhub workflow

docs/MAPPING_CASES.md
=> 3665 here maps documentation

Gemfile, Gemfile.lock
=> Migrate to new database_cleaner gem

Gemfile, Gemfile.lock
In your PR did you: Updated the version of mini_magick from 4.9.5 to 4.10.1
Fixes #3791
=> Updated mini_magick gem

config/initializers/carrier_wave.rb
Quite literally a hotfix for a missing end statement.  I'll let it go through CI but otherwise merge immediately.
=> A hotfix for missing end in carrierwave code

spec/rails_helper.rb
=> Randomize spec order when running rspec

config/initializers/rollbar.rb
=> Added dev environment to those where Rollbar isn't called #3841

.github/workflows/ci.yml, Gemfile, Gemfile.lock, app/assets/javascripts/maps.js, app/assets/stylesheets/maps.scss, app/controllers/maps_controller.rb, app/helpers/maps_helper.rb, app/models/case.rb, app/views/layouts/application.html.erb, app/views/maps/index.html.erb, config/initializers/redis.rb, spec/helpers/maps_helper_spec.rb, spec/views/maps/index.html.erb_spec.rb
=> 3652 link maps to cache

Gemfile, Gemfile.lock
=> Update carrierwave-optimizer gem

Gemfile, Gemfile.lock
=> Updates redis-namespace gem

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/views/layouts/application.html.erb, config/initializers/assets.rb, config/initializers/ckeditor.rb
=> Upgrades ckeditor gem

Gemfile, Gemfile.lock
=> Upgrades newrelic_rpm gem

Gemfile, Gemfile.lock
=> Upgrades httparty gem

app/views/cases/_form.html.erb
Temporarily disables photo upload for cases to avoid site outages while #4017 is in progress.
=> Temporarily disables photo upload for cases

Gemfile, Gemfile.lock
=> Upgrades recaptcha gem

.gitignore, app/models/case.rb, spec/rails_helper.rb
Removes 3 unnecessary TODO comments.  Part of the Code Quality Challenge
=> [ci skip] Removes unnecessary TODO comments

Gemfile, Gemfile.lock
=> Upgrades cloudflare-rails gem

app/views/cases/_form.html.erb
=> Restored upload block

Gemfile, Gemfile.lock
=> Add montrose gem to Gemfile

Makefile, app/assets/stylesheets/forms.scss, app/models/case.rb, app/views/cases/_form.html.erb, spec/models/case_spec.rb
**Issue:** Resolves #4040
**Description:**
Displays the number of characters left in the blurb field in new/edit case form
Turns to red when the characters left is lesser than 50
https://user-images.githubusercontent.com/29650842/135718518-494246d7-64e3-4404-ad63-7657bafb4e42.mov
=> Display characters left count for Blurb field in Case form

db/migrate/20211002101752_drop_calendar_events.rb, db/structure.sql
=> Add migration dropping calendar_events table

app/models/case.rb, app/models/cause_of_death.rb, config/application.rb, db/migrate/20211108220639_remove_cause_of_death_table.rb, db/structure.sql, lib/tasks/cases.rake, spec/lib/tasks/cases_rake_spec.rb
Removes the cause of death model and table and any references to them. Address issue #3005 
=> Remove cause of death model and table

app/views/layouts/application.html.erb
Move meta tags used for document rendering in the head element to ensure
consistent document rendering.
=> Move meta tags for document rendering

Gemfile.lock, README.md, app/views/conversations/_form.html.erb, dev_provisions/provision_application.sh, docs/DEVELOPMENT.md, docs/SETUP_LOCALLY_FULLSTACK.md
Upgrades the app to use Bundler 2.  Updates corresponding docker setup files and docs.  Addresses #4041 
=> Upgrade to Bundler 2

.gitignore, package-lock.json, package.json
Updates all npm packages to the latest version.  Updates additional npm packages based on result of `npm audit fix`.  Adds node modules directory to .gitignore
=> Update npm packages

app/views/cases/show.html.erb
Removes count queries from case show view, replacing it with calls to `size`.  Addresses Issue #4122 
=> Remove count queries from case show view

app/views/agencies/show.html.erb, app/views/cases/show.html.erb, config/locales/en.yml
Updates the show views of cases and agencies to use locales for cause of death and jurisdiction, respectively.  Addresses Issue #4044 
=> Use locales for jurisdiction and cause of death

app/views/cases/show.html.erb
=> Minor styling changes around cause of death

.github/workflows/ci.yml, .github/workflows/publish_docker_image.yml
This PR does not affect the application directly.  
Versions were updated for actions that needed to be moved to the latest versions of NodeJS.
=> Update action versions in workflows

spec/factories/users.rb
=> Fix intermittent test failure
